package policy

import (
	"encoding/json"
	"fmt"
	"strings"
)

// FormatJSON formats a compliance report as JSON
func FormatJSON(report *ComplianceReport) ([]byte, error) {
	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("failed to marshal report: %w", err)
	}
	return data, nil
}

// FormatMarkdown formats a compliance report as Markdown
func FormatMarkdown(report *ComplianceReport) string {
	var md strings.Builder

	md.WriteString("# Security Compliance Report\n\n")
	md.WriteString(fmt.Sprintf("**Generated**: %s\n", report.Timestamp.Format("2006-01-02 15:04:05")))
	md.WriteString(fmt.Sprintf("**Run ID**: %s\n\n", report.RunID))

	// Summary section
	md.WriteString("## Summary\n\n")
	md.WriteString(fmt.Sprintf("- **Total Findings**: %d\n", report.TotalFindings))
	md.WriteString(fmt.Sprintf("- **Policy Violations** (deny): %d\n", report.PolicyViolations))
	md.WriteString(fmt.Sprintf("- **Warnings**: %d\n", report.Warnings))
	md.WriteString(fmt.Sprintf("- **Allowed**: %d\n", report.Allowed))
	md.WriteString(fmt.Sprintf("- **Active Waivers**: %d\n", report.Waivers))
	md.WriteString(fmt.Sprintf("- **Policy Coverage**: %.1f%%\n\n", report.PolicyCoverage))

	// Policy violations by severity
	md.WriteString("## Policy Enforcement Summary\n\n")
	
	criticalCount := 0
	highCount := 0
	mediumCount := 0
	lowCount := 0
	
	for _, violation := range report.TopViolations {
		switch violation.Severity {
		case "critical":
			criticalCount += violation.Count
		case "high":
			highCount += violation.Count
		case "medium":
			mediumCount += violation.Count
		case "low":
			lowCount += violation.Count
		}
	}
	
	md.WriteString("### Violations by Severity\n\n")
	md.WriteString(fmt.Sprintf("- **Critical**: %d\n", criticalCount))
	md.WriteString(fmt.Sprintf("- **High**: %d\n", highCount))
	md.WriteString(fmt.Sprintf("- **Medium**: %d\n", mediumCount))
	md.WriteString(fmt.Sprintf("- **Low**: %d\n\n", lowCount))

	// Top violated policies
	if len(report.Policies) > 0 {
		md.WriteString("## Top Violated Policies\n\n")
		md.WriteString("| Policy | Action | Matches | Description |\n")
		md.WriteString("|--------|--------|---------|-------------|\n")
		
		// Sort policies by matches (descending)
		sortedPolicies := make([]PolicySummary, len(report.Policies))
		copy(sortedPolicies, report.Policies)
		sortPoliciesByMatches(sortedPolicies)
		
		// Show top 10
		limit := 10
		if len(sortedPolicies) < limit {
			limit = len(sortedPolicies)
		}
		
		for i := 0; i < limit; i++ {
			policy := sortedPolicies[i]
			desc := policy.Description
			if len(desc) > 50 {
				desc = desc[:47] + "..."
			}
			md.WriteString(fmt.Sprintf("| %s | %s | %d | %s |\n",
				policy.PolicyName,
				policy.Action,
				policy.Matches,
				desc))
		}
		md.WriteString("\n")
	}

	// Top CWE categories
	if len(report.TopViolations) > 0 {
		md.WriteString("## Top CWE Categories\n\n")
		md.WriteString("| Rank | CWE | Severity | Count | Action |\n")
		md.WriteString("|------|-----|----------|-------|--------|\n")
		
		for i, violation := range report.TopViolations {
			md.WriteString(fmt.Sprintf("| %d | %s | %s | %d | %s |\n",
				i+1,
				violation.CWEID,
				violation.Severity,
				violation.Count,
				violation.Action))
		}
		md.WriteString("\n")
	}

	// Waiver summary
	if report.Waivers > 0 {
		md.WriteString("## Waiver Summary\n\n")
		md.WriteString(fmt.Sprintf("- **Active Waivers**: %d\n", report.Waivers))
		md.WriteString(fmt.Sprintf("- **Waiver Rate**: %.1f%%\n\n", float64(report.Waivers)/float64(report.TotalFindings)*100))
	}

	// Recommendations
	md.WriteString("## Recommendations\n\n")
	
	if report.PolicyViolations > 0 {
		md.WriteString(fmt.Sprintf("- **Critical**: Address %d policy violations immediately\n", report.PolicyViolations))
	}
	
	if report.Warnings > 0 {
		md.WriteString(fmt.Sprintf("- **Review**: Investigate %d warnings for potential issues\n", report.Warnings))
	}
	
	if report.PolicyCoverage < 100 {
		md.WriteString(fmt.Sprintf("- **Coverage**: Improve policy coverage from %.1f%% to 100%%\n", report.PolicyCoverage))
	}
	
	if report.Waivers > 0 {
		md.WriteString(fmt.Sprintf("- **Waivers**: Review %d active waivers for expiration\n", report.Waivers))
	}
	
	md.WriteString("\n")

	// Footer
	md.WriteString("---\n\n")
	md.WriteString("*Generated by Coding Agent CLI*\n")

	return md.String()
}

// sortPoliciesByMatches sorts policies by match count in descending order
func sortPoliciesByMatches(policies []PolicySummary) {
	n := len(policies)
	for i := 0; i < n-1; i++ {
		for j := 0; j < n-i-1; j++ {
			if policies[j].Matches < policies[j+1].Matches {
				policies[j], policies[j+1] = policies[j+1], policies[j]
			}
		}
	}
}
